const carBrands = {
    Arcfox: "Arcfox",
    Acura: "Acura",
    Aion: "Aion",
    AlfaRomeo: "Alfa Romeo",
    AMC: "AMC",
    AstonMartin: "Aston Martin",
    Audi: "Audi",
    Baic: "Baic",
    Beijing: "Beijing",
    Bentley: "Bentley",
    BMW: "BMW",
    Brilliance: "Brilliance",
    Bugatti: "Bugatti",
    Buick: "Buick",
    BYD: "BYD",
    Cadillac: "Cadillac",
    Changan: "Changan",
    Changfeng: "Changfeng",
    Chery: "Chery",
    Chevrolet: "Chevrolet",
    Chrysler: "Chrysler",
    Citroen: "Citroen",
    CPI: "CPI",
    Dacia: "Dacia",
    Daewoo: "Daewoo",
    Daihatsu: "Daihatsu",
    Datsun: "Datsun",
    DMTelai: "DM Telai",
    Dodge: "Dodge",
    Dongfeng: "Dongfeng",
    DSAutomobiles: "DS Automobiles",
    Exeed: "Exeed",
    FAW: "FAW",
    Ferrari: "Ferrari",
    Fiat: "Fiat",
    Fisker: "Fisker",
    Ford: "Ford",
    Fortschritt: "Fortschritt",
    Foton: "Foton",
    GAZ: "GAZ",
    Geely: "Geely",
    Genesis: "Genesis",
    GMC: "GMC",
    GreatWall: "Great wall",
    Hafei: "Hafei",
    Haval: "Haval",
    Hiphi: "Hiphi",
    Honda: "Honda",
    Hongqi: "Hongqi",
    Huawei: "Huawei",
    Hummer: "Hummer",
    Hyster: "Hyster",
    Hyundai: "Hyundai",
    Infiniti: "Infiniti",
    IranKhodro: "Iran Khodro",
    Isuzu: "Isuzu",
    Iveco: "Iveco",
    JAC: "JAC",
    Jaguar: "Jaguar",
    Jeep: "Jeep",
    Jetour: "Jetour",
    Kama: "Kama",
    Karsan: "Karsan",
    Kia: "Kia",
    Lamborghini: "Lamborghini",
    Lancia: "Lancia",
    LandRover: "Land Rover",
    LeapMotor: "Leap Motor",
    Lexus: "Lexus",
    Lifan: "Lifan",
    Lincoln: "Lincoln",
    Linde: "Linde",
    Lixiang: "Lixiang",
    Lonking: "Lonking",
    Lotus: "Lotus",
    LTI: "LTI",
    Maserati: "Maserati",
    Maybach: "Maybach",
    Mazda: "Mazda",
    Mclaren: "Mclaren",
    MercedesBenz: "Mercedes-Benz",
    Mercury: "Mercury",
    MG: "MG",
    Mini: "Mini",
    Mitsubishi: "Mitsubishi",
    Mitsuoka: "Mitsuoka",
    Moskvich: "Moskvich",
    Neta: "Neta",
    Niewiadow: "Niewiadow",
    NIO: "NIO",
    Nissan: "Nissan",
    Opel: "Opel",
    Peugeot: "Peugeot",
    Pontiac: "Pontiac",
    Porsche: "Porsche",
    Proton: "Proton",
    Renault: "Renault",
    RenaultSamsung: "Renault Samsung",
    Roewe: "Roewe",
    RollsRoyce: "Rolls-Royce",
    Rover: "Rover",
    Saab: "Saab",
    Saleen: "Saleen",
    Saturn: "Saturn",
    Scion: "Scion",
    Seat: "Seat",
    Skoda: "Skoda",
    Skywell: "Skywell",
    Smart: "Smart",
    Soueast: "Soueast",
    Ssangyong: "Ssangyong",
    Subaru: "Subaru",
    Suzuki: "Suzuki",
    Tata: "Tata",
    Tesla: "Tesla",
    Toyota: "Toyota",
    UAZ: "UAZ",
    VAZ: "VAZ",
    Volkswagen: "Volkswagen",
    Volvo: "Volvo",
    Voyah: "Voyah",
    Xingtai: "Xingtai",
    Xpeng: "Xpeng",
    YTO: "YTO",
    YuanxinEnergys: "Yuanxin Energy's",
    ZAZ: "ZAZ",
    Zeekr: "Zeekr",
    Zukida: "Zukida",
    Zxauto: "Zxauto"
  };

  export const carBrandsArray = Object.keys(carBrands);