import type { Metadata } from "next";
import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Container } from "@/components/container";
import { MobileBottomNavbar } from "@/components/mobile-bottom-navbar";

const font = Noto_Sans_Georgian({ subsets: ["georgian"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Container>
          <Navbar />
          {children}
          <MobileBottomNavbar />
        </Container>
      </body>
    </html>
  );
}
